"""empty message

Revision ID: 178aad537214
Revises: 
Create Date: 2026-05-18 15:13:42.669201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178aad537214'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=True),
    sa.Column('difficulty_level', sa.String(length=5), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('video_id', name=op.f('pk_videos'))
    )
    op.create_table('subtitles',
    sa.Column('subtitle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], name=op.f('fk_subtitles_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subtitle_id', name=op.f('pk_subtitles'))
    )
    op.create_table('ai_cards',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('subtitle_id', sa.Integer(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('ai_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['subtitle_id'], ['subtitles.subtitle_id'], name=op.f('fk_ai_cards_subtitle_id_subtitles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', name=op.f('pk_ai_cards'))
    )
    op.create_table('subtitle_analyses',
    sa.Column('subtitle_analysis_id', sa.Integer(), nullable=False),
    sa.Column('subtitle_id', sa.Integer(), nullable=False),
    sa.Column('target_term', sa.String(length=255), nullable=True),
    sa.Column('restored_sentence', sa.Text(), nullable=True),
    sa.Column('ja_translation', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_model_name', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['subtitle_id'], ['subtitles.subtitle_id'], name=op.f('fk_subtitle_analyses_subtitle_id_subtitles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subtitle_analysis_id', name=op.f('pk_subtitle_analyses'))
    )
    with op.batch_alter_table('subtitle_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtitle_analyses_subtitle_id'), ['subtitle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subtitle_analyses_subtitle_id'))

    op.drop_table('subtitle_analyses')
    op.drop_table('ai_cards')
    op.drop_table('subtitles')
    op.drop_table('videos')
    # ### end Alembic commands ###
