"""restored_sentenceカラムをsubtitle_analyzesテーブルより削除

Revision ID: 36f2f4d7a9d7
Revises: 178aad537214
Create Date: 2026-05-20 14:03:44.657042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f2f4d7a9d7'
down_revision = '178aad537214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_analyses', schema=None) as batch_op:
        batch_op.drop_column('restored_sentence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restored_sentence', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
