"""動画の再生時間情報を追加するためにVideosテーブルにカラムを追加

Revision ID: 4840260a573e
Revises: 60023edce649
Create Date: 2026-05-22 10:28:50.593209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4840260a573e'
down_revision = '60023edce649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
