"""AICardテーブルのfront, backカラムを削除

Revision ID: 60023edce649
Revises: 36f2f4d7a9d7
Create Date: 2026-05-21 13:51:10.245532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60023edce649'
down_revision = '36f2f4d7a9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_cards', schema=None) as batch_op:
        batch_op.drop_column('back')
        batch_op.drop_column('front')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('front', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('back', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
